[package]
name = "lrdas-artifact"
version = "0.1.0"
edition = "2021"
rust-version = "1.93"
publish = false

[dependencies]
ark-bls12-381 = { version = "=0.4.0", default-features = false, features = ["curve"] }
ark-ec = { version = "=0.4.2", default-features = false, features = ["std"] }
ark-ff = { version = "=0.4.2", default-features = false, features = ["std"] }
ark-poly = { version = "=0.4.2", default-features = false, features = ["std"] }
ark-serialize = { version = "=0.4.2", default-features = false, features = ["std", "derive"] }
rand = "=0.8.5"
rand_chacha = "=0.3.1"
serde = { version = "=1.0.193", features = ["derive"] }
serde_json = "=1.0.108"
sha2 = "=0.10.8"

[profile.release]
lto = "thin"
codegen-units = 1
